# Generated by Django 2.2.4 on 2019-09-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_alt',
            field=models.CharField(default='Image', max_length=50),
        ),
    ]
